### ISSUE TITLE
Title colors upgrade?

### ISSUE THREAD

**Issue by jmoravec01** [matej-kaska/ujepsoft#11]
from 
![image](https://github.com/matej-kaska/ujepsoft/assets/91320507/45183212-f672-4462-9f1c-74a8fa4ccd56)

to
![image](https://github.com/matej-kaska/ujepsoft/assets/91320507/f49c05fb-43d9-4dcc-84b1-715e0b1ffd8f)

```
.soft-title {
  background-image: linear-gradient(45deg, #4F3A41, #EB9762, #9F5449);
  background-clip: text;
  color: transparent;
}
```

**Comment by matej-kaska** [comment]
:D:D:D: Tak to je hrozný třeba
