### ISSUE TITLE
Firefox -> Comments

### ISSUE THREAD

**Issue by jmoravec01** [matej-kaska/ujepsoft#14]
FireFox remembers **text**. Can be sent  ("komentář úspěšně přidán") many times in a row but to GitHub won´t get all comments, just the **first** one.

If you always add file and let the text be empty, it will remember the old one and will be sent successfully and written to GitHub.
![image](https://github.com/matej-kaska/ujepsoft/assets/91320507/a9a003eb-0546-42de-bd40-08317e1d64e5)
above: first time added text + image, second and third got only image

Cache/cookies problem?

**Comment by matej-kaska** [comment]
Should be fixed

**Comment by jmoravec01** [comment]
Perfect, good job.
