### ISSUE TITLE
Misaligned University Logo on 21:9 Monitor

### ISSUE THREAD

**Issue by Boubik** [matej-kaska/ujepsoft#15]
Description

The university logo on the UJEP Soft platform is misaligned when viewed on a 21:9 monitor. The logo appears too far to the left, causing visual inconsistency.
Steps to Reproduce

    Open the UJEP Soft platform in Firefox on a 21:9 monitor.
    Ensure the resolution is set to Full HD (2560x1080) with the 21:9 aspect ratio.
    Observe the positioning of the university logo.

Expected Behavior

The university logo should be properly aligned with the rest of the header content, regardless of the monitor aspect ratio.
Actual Behavior

The university logo appears shifted to the left, disrupting the visual balance of the header.

![Screenshot 2024-05-15 at 20-14-08 UJEP Soft](https://github.com/matej-kaska/ujepsoft/assets/30127367/426c2f47-7316-471f-b237-514bfec73d1f)

**Comment by matej-kaska** [comment]
Should be fixed

**Comment by Boubik** [comment]
Great, it's fixed now. Marking this issue as closed.
