### ISSUE TITLE
Disappearing File Attachments

### ISSUE THREAD

**Issue by Boubik** [matej-kaska/ujepsoft#16]
I create an issue on UJEP Soft with pictures or other attachments, and they get added successfully. However, when I then comment on the issue (first comment) on GitHub, the images or attachments disappear.

Steps to Reproduce:

    Create an issue on UJEP Soft and add pictures or attachments.
    Verify that the images or attachments are visible.
    Comment on the issue on GitHub.
    Check to see if the images or attachments are still visible.

Expected Result:
The images or attachments should remain visible after commenting on the issue on GitHub.

Actual Result:
The images or attachments disappear after the first comment on GitHub.

![Screenshot 2024-05-15 at 21-12-50 UJEP Soft](https://github.com/matej-kaska/ujepsoft/assets/30127367/c8d3faa2-584d-4dd5-89a5-1682438d5b52)

![Screenshot 2024-05-15 at 21-13-00 UJEP Soft](https://github.com/matej-kaska/ujepsoft/assets/30127367/69665091-7a21-4a3c-9fbe-4228bcac13fd)

![Screenshot 2024-05-15 at 21-14-02 UJEP Soft](https://github.com/matej-kaska/ujepsoft/assets/30127367/12d1b548-b31d-475e-9ca5-5ce58a49d678)

**Comment by matej-kaska** [comment]
Should be fixed for Issue and Comment.

**Comment by Boubik** [comment]
Great, it's fixed now. Marking this issue as closed.
