### ISSUE TITLE
Inconsistent Display of Images Across Different Browsers/OS

### ISSUE THREAD

**Issue by Boubik** [matej-kaska/ujepsoft#17]
I found this issue while working with @jmoravec01. I'm experiencing an issue where images are visible on one PC but not on another.

Where I See the Image:

    Windows: Chrome, Edge, Firefox

Where I Don't See the Image:

    Linux: Firefox (Different PC)

Steps to Reproduce:

    1. On a Windows PC, create an issue on UJEP Soft and add images.
    2. Add more comments to the issue on the Windows PC.
    3. View the issue on a Linux PC using Firefox.
    4. Observe that the images are not visible on the Linux PC.

Expected Result:
The images should be visible on all browsers and operating systems.

Actual Result:
The images are visible on Windows but not on Linux Firefox.

Screenshots:

Windows (Chrome/Edge/Firefox):

![image](https://github.com/matej-kaska/ujepsoft/assets/30127367/a766cfc0-fca6-49a8-95f2-508ea353cf52)

Linux (Firefox):

![Screenshot 2024-05-15 at 21-27-31 UJEP Soft](https://github.com/matej-kaska/ujepsoft/assets/30127367/425d6ede-b9b8-435c-bb1c-2314b60786b0)

**Comment by matej-kaska** [comment]
Cannot test it right now, because I don't have linux on me rn. Could you please provide me some html?

**Comment by Boubik** [comment]
Here is the HTML file along with all the other files (CSS, JPGs, etc.).

[ujepsoft.zip](https://github.com/matej-kaska/ujepsoft/files/15339928/ujepsoft.zip)

**Comment by Boubik** [comment]
Thank you for addressing the issue. There is a small update; now it at least shows that there are some files/images. However, the issue is not fully resolved. The text is still the same as before, but the styling has changed. I made a clean build of the app to ensure accurate testing, but the issue persists.

**Updated Comment HTML (with images):**

```html
<div class="comment-header">
  <section class="profile-badge">
    <img src="https://avatars.githubusercontent.com/u/91320507?v=4&amp;s=40" class="picture" alt="profile" id="profilePicture">
    <label class="name" for="profilePicture" id="profileName">jmoravec01</label>
  </section>
</div>
<div class="body html-inner">
<p>gggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggg</p>
</div>
<section class="images-wrapper">
  <h2>Obrázky:</h2>
  <div class="images">
    <div class="image-wrapper">
      <img alt="images.jfif" src="http://localhost:8080/backend/media/images.jfif">
      <span class="image-title">images.jfif</span>
    </div>
  </div>
</section>
<div class="footer">
  <span>Vytvořeno: 15. 5. 2024</span>
  <span>Naposledy aktualizováno: 15. 5. 2024</span>
</div>
```

![Screenshot 2024-05-19 at 13-50-50 UJEP Soft](https://github.com/matej-kaska/ujepsoft/assets/30127367/12e353d7-e4f2-4d89-9682-c0d3733f0681)

Please let me know if you need any further information to resolve this issue.

**Comment by matej-kaska** [comment]
This looks like Firefox on Linux issue. Because the HTML looks good. I tried to replicate it, but I cannot run the wsl with gui, sooo, I think that I cannot fix that. But I Fixed the long comments.

**Comment by Boubik** [comment]
It seems this issue only affects the JFIF format. Other formats work normally as expected.
