### ISSUE TITLE
Pixel-peeping

### ISSUE THREAD

**Issue by jmoravec01** [matej-kaska/ujepsoft#18]
"**Vytvořit nabídku**"

Chromium-based has it obvious.
Firefox a lot less but stil it can be seen.

P is above the lower dot
![image](https://github.com/matej-kaska/ujepsoft/assets/91320507/eb5688c3-cfa4-4f24-b92e-db26e72ed817)

P is below the lower dot
![image](https://github.com/matej-kaska/ujepsoft/assets/91320507/60947af3-3feb-4bce-947c-269507a7662a)

**Comment by matej-kaska** [comment]
Should be fixed now

**Comment by jmoravec01** [comment]
Perfect.
