### ISSUE TITLE
Unable to Remove Repository After Triggering Bug in Issue #7

### ISSUE THREAD

**Issue by Boubik** [matej-kaska/ujepsoft#19]
Issue Description

After triggering the bug described in issue #7, I am unable to remove the repository associated with the problem. If I try to remove other repositories, I receive an error message. However, after refreshing the page, those repositories disappear as expected without the error.

Testing Setup:

    Operating System: Linux
    Browser: Firefox

Steps to Reproduce:

    1. Trigger the bug described in issue #7.
    2. Attempt to remove the problematic repository.
    3. Observe that the repository does not get removed and error message appears.
    4. Attempt to remove other repositories.
    5. Note that an error message appears, but after refreshing the page, the repositories are removed.

Expected Result:
The repositories should be removed without any error messages.

Actual Result:
The problematic repository cannot be removed, and other repositories show an error message before disappearing after a page refresh.

Screenshots:

![53mUBRL](https://github.com/matej-kaska/ujepsoft/assets/30127367/0d3561d4-46bd-4222-ba54-7b5d3f58f648)

**Comment by Boubik** [comment]
Tested on Linux with Chrome, and there is no problem removing the problematic repository.

**Comment by matej-kaska** [comment]
Could you please provide better step by step for triggering Issue #7 because I cannot reproduce it. Maybe I fixed it accidentally.

**Comment by Boubik** [comment]
One way to trigger it is by changing the tag (in ujepsoft).

**Comment by matej-kaska** [comment]
@Boubik what about this issue? Still happening?

**Comment by Boubik** [comment]
I can't trigger the problem anymore, so it should be fixed.
