### ISSUE TITLE
File as an attachment - tooltips

### ISSUE THREAD

**Issue by jmoravec01** [matej-kaska/ujepsoft#20]
Tooltips remember **last added image name** as you can see in the picture.

Right
![image](https://github.com/matej-kaska/ujepsoft/assets/91320507/e6e3add3-79f4-40aa-93af-8389deeadee9)

Wrong (should be "Nevybrán žádný soubor")
![image](https://github.com/matej-kaska/ujepsoft/assets/91320507/907afb0a-7bed-4101-8700-98993f5b5636)

Wrong - deleted file
![image](https://github.com/matej-kaska/ujepsoft/assets/91320507/51ca2505-ec89-4a8c-bcd1-6223d859c44c)

Wrong - remembers last added image
![image](https://github.com/matej-kaska/ujepsoft/assets/91320507/a2750ad4-a15d-4e79-919b-148ba3773143)

**Comment by matej-kaska** [comment]
Nice catch, should be fixed, please test it.

**Comment by jmoravec01** [comment]
Good job.
