### ISSUE TITLE
Unable to Change Tag on Existing Issue

### ISSUE THREAD

**Issue by Boubik** [matej-kaska/ujepsoft#21]
Issue Description

If I have already created an issue, I cannot change the tag (označení). The system indicates that the tag has been successfully changed, but no actual change occurs. This issue is present in both GitHub and UJEP Soft.

Steps to Reproduce:

    Create an issue with any tag (označení).
    Attempt to change the tag on the existing issue.
    Observe that the system displays a message indicating the tag was successfully changed.
    Check the issue to see if the tag has been updated.

Expected Result:
The tag should be updated successfully on both GitHub and UJEP Soft.

Actual Result:
The system indicates that the tag has been changed, but no actual change occurs in either GitHub or UJEP Soft.

Testing Setup:

    Operating System: Linux
    Browsers: Firefox, Chrome

Screenshots:

![Screenshot 2024-05-15 at 21-51-31 UJEP Soft](https://github.com/matej-kaska/ujepsoft/assets/30127367/189143f8-1c65-4a75-a032-e83523cf3861)

![Screenshot 2024-05-15 at 21-51-39 UJEP Soft](https://github.com/matej-kaska/ujepsoft/assets/30127367/85805ac3-3757-4af4-be61-53e682a6605a)

![Screenshot 2024-05-15 at 21-51-44 UJEP Soft](https://github.com/matej-kaska/ujepsoft/assets/30127367/858169f0-2fa1-499e-8a1d-76faf6754edb)

**Comment by matej-kaska** [comment]
Should be fixed, please test it

**Comment by Boubik** [comment]
Okay, it's somewhat fixed now. Although the message says it failed (as shown in the screenshot), the changes are reflected on GitHub. However, you still can't access the issues or remove the problematic repository, as described in issue #19.

**Comment by matej-kaska** [comment]
It worked for me, try to delete all issues in the db.

**Comment by Boubik** [comment]
Okay, removing the database fixed the issue.
