### ISSUE TITLE
Images from GitHub

### ISSUE THREAD

**Issue by jmoravec01** [matej-kaska/ujepsoft#24]
If you upload images via GitHub with no text, there will be text of url to the image on GitHub.
Is it possible to make a text empty if there are just images?

**It can look like this if we send 15 images.**

![obrazky_z_githubu](https://github.com/matej-kaska/ujepsoft/assets/91320507/ef3ed8c0-bfa0-49b3-a442-91908b5c5bab)

**Comment by matej-kaska** [comment]
Uploading files to github doesnt work rn.

**Comment by matej-kaska** [comment]
Should be working I guess?

**Comment by matej-kaska** [comment]
Duplicate of #22

**Comment by jmoravec01** [comment]
Done, GJ.
