### ISSUE TITLE
Emojis as a title/key-word/description

### ISSUE THREAD

**Issue by jmoravec01** [matej-kaska/ujepsoft#25]
Is it possible to "block" emojis as a input for title/key-word? It looks weird.

![image](https://github.com/matej-kaska/ujepsoft/assets/91320507/ce334682-9ac6-4631-964a-2fb227d2529b)

**Comment by matej-kaska** [comment]
I think we should leave up to the user, if someone wants to add emojis, then he should add it. We shouldn't restrict this.

**Comment by jmoravec01** [comment]
Okey.
