### ISSUE TITLE
Enhancement: Remove Text After Successfully Adding Repository

### ISSUE THREAD

**Issue by Boubik** [matej-kaska/ujepsoft#26]
**Description:**

I would like to request an enhancement for the UJEP Soft application. After successfully adding a repository, the text input field should be cleared automatically. This will improve the user experience by indicating that the repository was added successfully and providing a clean state for any subsequent additions.

**Steps to Reproduce:**
1. Navigate to the "Administrace" section on UJEP Soft.
2. Enter a repository URL in the input field.
3. Click the "Přidat" button to add the repository.

**Current Behavior:**
The repository is added successfully, but the text input field remains filled with the previously entered URL.

**Expected Behavior:**
The text input field should be cleared automatically after a repository is successfully added.

**Screenshots:**

- Current State After Adding Repository:  
![Screenshot 2024-05-18 at 16-25-40 UJEP Soft](https://github.com/matej-kaska/ujepsoft/assets/30127367/053de8bb-a8c2-41ac-8641-b23fbb87ae2d)

**Environment:**
- OS: Linux
- Browser: Firefox

Please let me know if you need any further information to implement this enhancement.

**Comment by matej-kaska** [comment]
Nice catch, I have added it.

**Comment by Boubik** [comment]
Functioning as intended.
