### ISSUE TITLE
Display Repository Owner Before Repository Name

### ISSUE THREAD

**Issue by Boubik** [matej-kaska/ujepsoft#27]
**Description:**

I would like to request an enhancement for the UJEP Soft application. To avoid confusion when repositories have the same name but are owned by different users, the repository owner's name should be displayed before the repository name. This will help users to easily distinguish between repositories with similar names from different owners.

**Current Behavior:**
Repositories are listed by their names without showing the owner's name, which can lead to confusion if multiple repositories have the same name. As shown in the screenshot below, there is no visual differentiation between the two repositories named `test1` owned by different users (`Boubik` and `jakubmoravec01`).

**Expected Behavior:**
The repository list should display the owner's name before the repository name to clearly indicate which user owns each repository.

**Example:**
Instead of:
- `test1`
- `test1`

It should display:
- `Boubik / test1`
- `jakubmoravec01 / test1`

**Screenshots:**

- Current Repository List:  
![Screenshot 2024-05-18 at 21-44-04 UJEP Soft](https://github.com/matej-kaska/ujepsoft/assets/30127367/8b3421ca-ad55-416b-9b91-b46f4b55c1fd)

Please let me know if you need any further information to implement this enhancement.

**Comment by matej-kaska** [comment]
You are right, I have added it.

**Comment by Boubik** [comment]
That looks much better!
