### ISSUE TITLE
Weird Displaying of Markdown Text in Nabídky

### ISSUE THREAD

**Issue by Boubik** [matej-kaska/ujepsoft#28]
**Description:**

I'm encountering an issue where Markdown text is displayed incorrectly on UJEP Soft when using Linux Firefox. The formatting does not appear as expected. Please see the attached screenshots for reference.

**Steps to Reproduce:**
1. Navigate to an issue on UJEP Soft.
2. View the issue using Linux Firefox.

**Expected Behavior:**
Markdown text should be displayed correctly with proper formatting.

**Actual Behavior:**
Markdown text is displayed weirdly, as shown in the screenshots below.

**Screenshots:**

- Incorrect Display of Markdown Text:  
![Screenshot 2024-05-18 at 22-01-36 UJEP Soft](https://github.com/matej-kaska/ujepsoft/assets/30127367/38e4edef-4470-4326-91bd-d1993dfdf221)

- Expected Display of Markdown Text:  
![Screenshot 2024-05-18 at 22-07-23 Issues · matej-kaska_ujepsoft](https://github.com/matej-kaska/ujepsoft/assets/30127367/152b22b9-45cc-4b83-8f8e-0a9a60649e5b)

**Environment:**
- OS: Linux
- Browser: Firefox

Please let me know if you need any further information to resolve this issue.

**Comment by matej-kaska** [comment]
Should be fixed now.

**Comment by Boubik** [comment]
Seems to be fixed, thanks!
