### ISSUE TITLE
Text Not Wrapping in "Nabídky" Section

### ISSUE THREAD

**Issue by Boubik** [matej-kaska/ujepsoft#29]
**Description:**
I'm encountering an issue where the text is not wrapping correctly in the "Nabídky" section when using Linux Firefox. Please see the attached screenshot for reference.

**Steps to Reproduce:**
1. Navigate to the "Nabídky" section on UJEP Soft.
2. Use Linux Firefox to view the page.
3. Observe the text not wrapping as expected.

**Expected Behavior:**
Text should wrap properly to fit within the container.

**Actual Behavior:**
Text does not wrap, causing it to overflow outside the container. An example of this issue can be seen in the following GitHub issue: [Example Issue](https://github.com/jakubmoravec01/test1/issues/1).

**Screenshot:**
![Screenshot 2024-05-19 at 13-50-50 UJEP Soft](https://github.com/matej-kaska/ujepsoft/assets/30127367/efdabcc7-cff6-4631-a3ab-29af0ef6ab4b)

**Environment:**
- OS: Linux
- Browser: Firefox

Please let me know if you need any further information to resolve this issue.

**Comment by matej-kaska** [comment]
That's not Nabídky, but I fixed it.

**Comment by Boubik** [comment]
Sorry for the mistake, but it's fixed now.
