### ISSUE TITLE
Kdyby ses nudil -> ALT+0160 (blank space)

### ISSUE THREAD

**Issue by jmoravec01** [matej-kaska/ujepsoft#3]
![Snímek obrazovky 2023-12-18 234814](https://github.com/matej-kaska/ujepsoft/assets/91320507/10342a2c-304f-44ad-afc8-69a030e5d9fc)
![Snímek obrazovky 2023-12-18 234827](https://github.com/matej-kaska/ujepsoft/assets/91320507/403ee5cd-6f56-49d5-852c-b3435b512af4)

**Comment by jmoravec01** [comment]
Ale do klíčových to nebere.

**Comment by matej-kaska** [comment]
fixed
