### ISSUE TITLE
"Nezobrazovat uzavřené" Selection Not Remembered

### ISSUE THREAD

**Issue by Boubik** [matej-kaska/ujepsoft#30]
**Description:**
I'm encountering an issue where the "Nezobrazovat uzavřené" selection is not remembered when navigating to an issue and then returning back in UJEP Soft. This problem occurs when using Linux Firefox. The selection resets back to default instead of remembering the last state. Please see the attached screenshot for reference.

**Steps to Reproduce:**
1. Open UJEP Soft in Linux Firefox.
2. Select "Nezobrazovat uzavřené" in the "Problémy/Úkoly (Issues)" section.
3. Navigate to an issue.
4. Return back to the "Problémy/Úkoly (Issues)" section.
5. Observe that the "Nezobrazovat uzavřené" selection has reset to default.

**Expected Behavior:**
The "Nezobrazovat uzavřené" selection should be remembered and persist when navigating back to the "Problémy/Úkoly (Issues)" section.

**Actual Behavior:**
The selection resets back to default instead of remembering the last state.

**Screenshot:**
![Screenshot 2024-05-21 at 20-57-40 UJEP Soft](https://github.com/matej-kaska/ujepsoft/assets/30127367/dea45aa6-6ef4-450f-86db-df304225b317)

**Environment:**
- OS: Linux
- Browser: Firefox

Please let me know if you need any further information to resolve this issue.

**Comment by matej-kaska** [comment]
I have added it. Please try it.

**Comment by Boubik** [comment]
That works much better!
