### ISSUE TITLE
Padding Issue on the Bottom of the Page

### ISSUE THREAD

**Issue by Boubik** [matej-kaska/ujepsoft#35]
**Description:**
I'm encountering a problem with the padding on the bottom of the page when trying to change an issue in UJEP Soft. This issue prevents me from accessing the "Změnit issue" button. The problem occurs while using Safari on an iPhone with iOS 17. Please see the attached video for reference.

**Steps to Reproduce:**
1. Open UJEP Soft on Safari using an iPhone with iOS 17.
2. Navigate to the "Changing Issue" page.
3. Try to scroll to the bottom of the page.
4. Observe that the padding issue prevents access to the "Změnit issue" button.

**Expected Behavior:**
The "Změnit issue" button should be accessible without any padding issues at the bottom of the page.

**Actual Behavior:**
The padding at the bottom of the page prevents access to the "Změnit issue" button.

**Video:**

https://github.com/matej-kaska/ujepsoft/assets/30127367/8f7f6c9b-6b45-4ca3-9750-c1a645114835

**Environment:**
- Device: iPhone
- OS: iOS 17
- Browser: Safari

Please let me know if you need any further information to resolve this issue.

**Comment by Boubik** [comment]
The issue is present not only on the "Změnit issue" page but also on the "Vytvořit issue" and "Vytvořit nabídku" pages.

**Comment by matej-kaska** [comment]
Should be fixed now.

**Comment by matej-kaska** [comment]
![image](https://github.com/matej-kaska/ujepsoft/assets/12019437/3926ba2b-50cc-4c7e-ba06-eb4db3b8ed45)

not happening for me
