### ISSUE TITLE
Add Reopen Issue Functionality in UJEP Soft

### ISSUE THREAD

**Issue by Boubik** [matej-kaska/ujepsoft#37]
**Description:**
I would like to request an enhancement to add the ability to reopen issues in UJEP Soft. Currently, there is no way to reopen an issue once it has been closed. This functionality is essential for cases where issues may need to be revisited or were closed prematurely. In GitHub, the ability to reopen issues is available and frequently used, making it a valuable feature for effective issue tracking and management.

**Steps to Reproduce:**
1. Close an issue in UJEP Soft.
2. Observe that there is no option to reopen the issue.

**Expected Behavior:**
There should be a "Reopen Issue" button or option available to allow users to reopen closed issues.

**Actual Behavior:**
There is no way to reopen an issue once it has been closed.

**Justification:**
In GitHub, the ability to reopen issues is available and commonly used. This feature allows for better management of issues, especially in cases where an issue needs to be revisited or was closed by mistake. Implementing this functionality in UJEP Soft would greatly improve its usability and efficiency.

Please let me know if you need any further information to implement this enhancement.

**Comment by matej-kaska** [comment]
I am against that, I did this intentionally, because users will probably not know what does this mean and will open another one anyway.
