### ISSUE TITLE
Administration - input window is shrinking

### ISSUE THREAD

**Issue by jmoravec01** [matej-kaska/ujepsoft#38]
**affected browsers** : Edge, Chrome, FireFox

After upgrading CSS for responsivness there is this "shrinking" of input window for GitHub repos. You can see it after entering/reloading page (/repo-administration). 

There was a similar problem in the beginning of the project with "jumping text" in FireFox on the homepage.

https://github.com/matej-kaska/ujepsoft/assets/91320507/30b1212d-8aba-4408-a02d-05002bc2636e

**Comment by matej-kaska** [comment]
Should be fixed

**Comment by jmoravec01** [comment]
Perfect.
