### ISSUE TITLE
Grammatical Error on Návody Page

### ISSUE THREAD

**Issue by Boubik** [matej-kaska/ujepsoft#39]
**Description:**
There is a grammatical error on the Návody page in UJEP Soft. The text contains a mistake that needs correction. The current text and the corrected version are provided below.

**Current Text:**
Zde naleznete návody veškeré potřebné návody. Pokud ovšem narazíte na jakýkoliv problém, neváhejte kontaktovat na administátora pavel.beranek@ujep.cz.

**Corrected Text:**
Zde naleznete veškeré potřebné návody. Pokud ovšem narazíte na jakýkoliv problém, neváhejte kontaktovat administrátora na e-mailu pavel.beranek@ujep.cz.

**Screenshot:**
![Screenshot 2024-05-28 at 17-32-18 UJEP Soft](https://github.com/matej-kaska/ujepsoft/assets/30127367/d5e77849-70cf-4023-8395-df5948201533)

**Comment by matej-kaska** [comment]
Fixed.
