### ISSUE TITLE
Landing page - space between text

### ISSUE THREAD

**Issue by jmoravec01** [matej-kaska/ujepsoft#4]
**Firefox browser.**
![firefox](https://github.com/matej-kaska/ujepsoft/assets/91320507/ba29f92f-63ec-4a61-9554-801ea3c09a8e)

**Chromium based browsers (Edge, Opera).**
![chromium](https://github.com/matej-kaska/ujepsoft/assets/91320507/9c24935f-fdfe-457d-b00f-f69bcc649eab)

**Comment by matej-kaska** [comment]
![image](https://github.com/matej-kaska/ujepsoft/assets/12019437/48ca66f3-e1c7-47a4-959b-ea635c7729e0)
It's because of these &lt;br&gt; tags, dont mind that, this will be removed on deploy.
