### ISSUE TITLE
Adding already added repo

### ISSUE THREAD

**Issue by jmoravec01** [matej-kaska/ujepsoft#40]
Maybe we have discussed it but would it be possible to add another pop-up text about repos which are already in the list?

There might be a huge list and it would be fine to know if some repo was already in the database.

So maybe change _Repozitář byl úspěšně přidán do databáze!_ to something like _Repozitář se již nachází v databázi!_ ?

![image](https://github.com/matej-kaska/ujepsoft/assets/91320507/58219ac7-cfb1-46cd-90bd-01ff287c06b1)

![image](https://github.com/matej-kaska/ujepsoft/assets/91320507/5f68e436-5374-4fcb-ab5f-96977e7745e3)

This is not necessary but it seems fine to me.

**Comment by matej-kaska** [comment]
If it was there and someone would try to add same repo, the text would be here and he would try to add another one, it would confuse him, that this repo is there too.
