### ISSUE TITLE
Edit Issue - Need to add label (označení)

### ISSUE THREAD

**Issue by jmoravec01** [matej-kaska/ujepsoft#41]
After trying to edit Issue there is necessity to add **label** but GitHub Issues does not require one. 

Wouldn´t it be better to let user choose if there is some label necessary?

![image](https://github.com/matej-kaska/ujepsoft/assets/91320507/d2572e63-8a3a-41fd-9ae0-3c608729a0ff)

**Comment by matej-kaska** [comment]
Nope, UJEP Soft issue must have label.
