### ISSUE TITLE
CSS on Mobile - Administration button

### ISSUE THREAD

**Issue by jmoravec01** [matej-kaska/ujepsoft#42]
BEFORE
![image](https://github.com/matej-kaska/ujepsoft/assets/91320507/60ec45d6-8828-4743-8156-ed7154f14287)

AFTER
![image](https://github.com/matej-kaska/ujepsoft/assets/91320507/140e5619-9920-4184-80ce-cbf3d4159fca)

Plus makes it weird. I have wanted to follow other sites with "+ Přidat nabídku/Issue".
![image](https://github.com/matej-kaska/ujepsoft/assets/91320507/a70978f7-dec6-47d8-9b5b-e8d769bed037)

**SOLUTION**
I can imagine that on smartphone there will be just icon of "+".

**Comment by matej-kaska** [comment]
Should be fixed

**Comment by jmoravec01** [comment]
Done. GJ
