### ISSUE TITLE
CSS on Mobile - longer repo names

### ISSUE THREAD

**Issue by jmoravec01** [matej-kaska/ujepsoft#43]
![image](https://github.com/matej-kaska/ujepsoft/assets/91320507/6a15beb4-0603-4171-b05b-d603166ca2d9)

Probably will need to make titles/names scrollable?

**Comment by matej-kaska** [comment]
Should be fixed

**Comment by jmoravec01** [comment]
Fixed but profile pictures disappeared.

**Comment by jmoravec01** [comment]
Fixed. GJ
