### ISSUE TITLE
CSS - Nabídky/Offers - weird hover on text

### ISSUE THREAD

**Issue by jmoravec01** [matej-kaska/ujepsoft#44]
If there is a longer text in the offer title it will divide into two rows but the second one is not "_whole_". It is clickable but looks weird. Also there is a gap between the first and the second row (why? - it is one <a> tag).

https://github.com/matej-kaska/ujepsoft/assets/91320507/09585770-280a-4bf3-83dc-2ebe57794bd1

We have discussed underlines which are not sometimes visible because of font but this is new (at least I think).

**Comment by matej-kaska** [comment]
Should be fixed

**Comment by jmoravec01** [comment]
Perfect. GJ
