### ISSUE TITLE
Tags can´t be deleted

### ISSUE THREAD

**Issue by jmoravec01** [matej-kaska/ujepsoft#46]
After trying to edit Offer -> **deleting** tag -> nothing happens.

If you try to delete for example all tags (2 tags = finance/money) it will say it needs at least **one** tag. So you add for example tag "test" but instead of deleting both old ones and adding new one, it will just add the new one to the old ones.

So now you will have tags: **finance/money/test**

Expected was: **test**

**Comment by matej-kaska** [comment]
Should be fixed

**Comment by jmoravec01** [comment]
Perfect!
