### ISSUE TITLE
Notifications - filesize

### ISSUE THREAD

**Issue by jmoravec01** [matej-kaska/ujepsoft#52]
Notifications about filesize limit might get lost behind the form during creating/editing of Nabídky.
- only if there are more files involved
- can be completely behind the form
- tested on Edge + Firefox

edge
![alert-edge](https://github.com/user-attachments/assets/df8ef51b-ae00-4138-a930-3b603b25028d)

firefox
![alert-firefox](https://github.com/user-attachments/assets/c52ee036-1d2d-437a-895b-a40671f489f3)

**Comment by matej-kaska** [comment]
Should be fixed

**Comment by jmoravec01** [comment]
Checked with Edge and Firefox. Seems solved. GJ
