### ISSUE TITLE
Behavior of the 512MB Limit

### ISSUE THREAD

**Issue by jmoravec01** [matej-kaska/ujepsoft#58]
The 512MB file size limit behaves differently depending on whether you are creating or editing files:

**Creating:** ,
There is a 512MB limit on the total size of files you can create. This is straightforward and works as expected.

**Editing:** 
When editing files, it appears that each edit session effectively has its own 512MB limit. This means you can exceed the original 512MB limit by repeatedly clicking "edit" and adding more content, effectively creating a cumulative limit of x * 512MB, where x is the number of times you have clicked "edit."

**Comment by jmoravec01** [comment]
Works same for Localhost and Server.

**Comment by matej-kaska** [comment]
I have implemented logic for checking, but didnt finish it. Now everything should work as expected.

**Comment by jmoravec01** [comment]
Works like a charm. Good job.
