### ISSUE TITLE
Issues bug

### ISSUE THREAD

**Issue by jmoravec01** [matej-kaska/ujepsoft#7]
After adding comment to issue and refreshing [website](https://ujepsoft.boubik.cz/issues) right after - there is 1-2s bug of not loading any issues.

**Comment by jmoravec01** [comment]
After deleting repo and re-adding it works fine. This looks like a database bug.

**Comment by matej-kaska** [comment]
Should be fixed

**Comment by jmoravec01** [comment]
Issue was created via GitHub. When trying to reaload page to see all new Issues you can´t see any -> "Došlo k neočekávané chybě".

EDGE, CHROME, FIREFOX + @Boubik has the same issue

**Comment by matej-kaska** [comment]
Maybe fixed? Need more details.

**Comment by jmoravec01** [comment]
Seems fixed.
