### ISSUE TITLE
Nabídky/issues mají stejnou error message - do budoucna

### ISSUE THREAD

**Issue by jmoravec01** [matej-kaska/ujepsoft#9]
![image](https://github.com/matej-kaska/ujepsoft/assets/91320507/8b35ca3d-7702-42ef-a7ef-bd4ad990071d)

"_Název nabídky musí být minimálně 6 znaků dlouhý_" tento text je jak u nabídek/issues -> nedodržení správného termínu.

Nachází se na 22. řádku ve validationSchemas.tsx

**Comment by matej-kaska** [comment]
nice

**Comment by matej-kaska** [comment]
Should be fixed

**Comment by jmoravec01** [comment]
Možná odstranit "raw"? 

![image](https://github.com/matej-kaska/ujepsoft/assets/91320507/ba016cd0-b765-4451-a617-43fff5f19ff7)


Zde chybí jen "**s**" v "stikněte"

![image](https://github.com/matej-kaska/ujepsoft/assets/91320507/250f62db-b2aa-4a56-b41b-339785322818)

**Comment by matej-kaska** [comment]
"raw" should be "raw" because the editor is in html. So there are unvisible tags. Fixed typo.

**Comment by jmoravec01** [comment]
Good job! Like the swap from "Toto pole je povinné!" to "Název musí být minimálně 6 znaků dlouhý!" in title for issues/nabídek.

**Comment by jmoravec01** [comment]
But found another bug for EDGE/FIREFOX/CHROME.

empty
![image](https://github.com/matej-kaska/ujepsoft/assets/91320507/d60edee2-e28e-401f-94bf-fec82583ccc8)

title less than 6 letters
![image](https://github.com/matej-kaska/ujepsoft/assets/91320507/c18f980d-ba32-45f5-aa8d-07716bda85c1)

After deleting these 5 letters it will get back to "Toto pole je povinné!". **WORKS** well with Issues + Nabídky.

This **does not work** with description either with Nabídky or Issues. There is "Toto pole je povinné!" only if you try to submit empty  description. If you try to write something and then delete whole text, it will stay on "Popis musí být minimálně 32 raw znaků dlouhý!".

submitting empty
![image](https://github.com/matej-kaska/ujepsoft/assets/91320507/02bc2488-6ca6-42ff-8b1a-63debdf186d8)

deleting some text
![image](https://github.com/matej-kaska/ujepsoft/assets/91320507/e2558bb2-687f-4c3d-9a04-e2172e76e0db)


**WHAT WAS EXPECTED**
After deleting text in description for Issues + Nabídky I would expect "Toto pole je povinné!" as it is in Title in both.

**Comment by matej-kaska** [comment]
This is good behaviour, because when it's empty there is "", when something was written there and removed after then there is only "<p></p>/n", I would have to make a lot of edge cases for this one little """""error"""".

**Comment by jmoravec01** [comment]
Understand. Good job.
